<?php
class HTTP_STATUS {
  const HTTP_OK = 200;
  const HTTP_CREATED = 201;
  const HTTP_NO_CONTENT = 204;
  const HTTP_PARTIAL_CONSENT = 206;
  const HTTP_BAD_REQUEST = 400;
  const HTTP_UNAUTHORIZED = 401;
  const HTTP_FORBIDDEN = 403;
  const HTTP_NOT_FOUND = 404;
  const HTTP_INTERNAL_SERVICE_ERROR = 500;
  const HTTP_INTERNAL_SERVICE_NOT_AVAILABLE = 503;
}
